"""add collection activities

Revision ID: 5e64762eb612
Revises: 876db3077147
Create Date: 2026-08-30 17:57:11.458242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e64762eb612'
down_revision: Union[str, None] = '876db3077147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=150), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('outcome', sa.String(length=100), nullable=False),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_action', sa.String(length=150), nullable=True),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['collection_cases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_activities_case_id'), 'collection_activities', ['case_id'], unique=False)
    op.create_index(op.f('ix_collection_activities_tenant_id'), 'collection_activities', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_activities_tenant_id'), table_name='collection_activities')
    op.drop_index(op.f('ix_collection_activities_case_id'), table_name='collection_activities')
    op.drop_table('collection_activities')
    # ### end Alembic commands ###
