"""add contact attempts

Revision ID: 711f88c0c06d
Revises: 5e64762eb612
Create Date: 2026-08-30 18:21:59.626625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711f88c0c06d'
down_revision: Union[str, None] = '5e64762eb612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('collector', sa.String(length=150), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('outcome', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('contacted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['collection_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_attempts_case_id'), 'contact_attempts', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_attempts_case_id'), table_name='contact_attempts')
    op.drop_table('contact_attempts')
    # ### end Alembic commands ###
