"""update case activities columns

Revision ID: 876db3077147
Revises: eae5500bfbba
Create Date: 2026-08-30 14:34:46.340487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876db3077147'
down_revision: Union[str, None] = 'eae5500bfbba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_activities', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('case_activities', sa.Column('channel', sa.String(length=50), nullable=True))
    op.alter_column('case_activities', 'activity_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_case_activities_created_at'), 'case_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_case_activities_tenant_id'), 'case_activities', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'case_activities', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'case_activities', type_='foreignkey')
    op.drop_index(op.f('ix_case_activities_tenant_id'), table_name='case_activities')
    op.drop_index(op.f('ix_case_activities_created_at'), table_name='case_activities')
    op.alter_column('case_activities', 'activity_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('case_activities', 'channel')
    op.drop_column('case_activities', 'tenant_id')
    # ### end Alembic commands ###
