"""add case activities

Revision ID: ad882fc4d113
Revises: c2f1bef715df
Create Date: 2026-08-30 13:40:44.497608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad882fc4d113'
down_revision: Union[str, None] = 'c2f1bef715df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['collection_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_activities_activity_type'), 'case_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_case_activities_case_id'), 'case_activities', ['case_id'], unique=False)
    op.drop_index('ix_collection_cases_priority', table_name='collection_cases')
    op.drop_index('ix_collection_cases_status', table_name='collection_cases')
    op.drop_index('ix_municipal_accounts_account_number', table_name='municipal_accounts')
    op.drop_index('ix_municipal_accounts_customer_id', table_name='municipal_accounts')
    op.drop_index('ix_municipal_accounts_property_id', table_name='municipal_accounts')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_municipal_accounts_property_id', 'municipal_accounts', ['property_id'], unique=False)
    op.create_index('ix_municipal_accounts_customer_id', 'municipal_accounts', ['customer_id'], unique=False)
    op.create_index('ix_municipal_accounts_account_number', 'municipal_accounts', ['account_number'], unique=False)
    op.create_index('ix_collection_cases_status', 'collection_cases', ['status'], unique=False)
    op.create_index('ix_collection_cases_priority', 'collection_cases', ['priority'], unique=False)
    op.drop_index(op.f('ix_case_activities_case_id'), table_name='case_activities')
    op.drop_index(op.f('ix_case_activities_activity_type'), table_name='case_activities')
    op.drop_table('case_activities')
    # ### end Alembic commands ###
