"""add financial transactions

Revision ID: c56e3b18756a
Revises: 711f88c0c06d
Create Date: 2026-08-30 18:32:20.687330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c56e3b18756a'
down_revision: Union[str, None] = '711f88c0c06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_transactions_account_id'), 'financial_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_reference'), 'financial_transactions', ['reference'], unique=False)
    op.create_index(op.f('ix_financial_transactions_tenant_id'), 'financial_transactions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_transaction_date'), 'financial_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_financial_transactions_transaction_type'), 'financial_transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_transactions_transaction_type'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_transaction_date'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_tenant_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_reference'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_account_id'), table_name='financial_transactions')
    op.drop_table('financial_transactions')
    # ### end Alembic commands ###
